### ISSUE TITLE
Add support for the `CrowdinVendorManualTaskCreateForm`

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#107]
API reference: [api.projects.tasks.post](https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post)

**Comment by sabarish98** [comment]
@andrii-bodnar : I would like to work on this. I believe since the implementation of the API is already there, adding the Request Body Schema extending the AddTaskRequest class should add the support for `CrowdinVendorManualTaskCreateForm`. Correct me if I am wrong

**Comment by andrii-bodnar** [comment]
@sabarish98 yes, you're right, the API is already here and you just need to extend the `AddTaskRequest`
