### ISSUE TITLE
Bundles API enhancement

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#125]
We've added a few new API endpoints to manage Bundles in Crowdin - https://developer.crowdin.com/api/v2/#tag/Bundles

It would be great to add the new methods to the corresponding class - [BundlesApi.java](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/bundles/BundlesApi.java) and include tests.

**Comment by Aveti79** [comment]
Hi, 
I would like to try to work with this issue.
Im also already started trying to work with this, but after writing tests to download endpoint i discovered that expireIn has been deserialized without reading minutes. I think that possible issue could be in Json deserializer but can't find it.

![1wyc](https://user-images.githubusercontent.com/68544494/225710323-cd23faf6-35e8-4f91-9218-45e6aff86e2e.PNG)

**Comment by andrii-bodnar** [comment]
@Aveti79 great, thank you! I will assign this issue to you

I think there should be the same deserializing behavior as we have for the [api.projects.translations.builds.download.download](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.download.download). You can use it for a reference
