### ISSUE TITLE
Add `isMultilingual` to the Bundle model

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#134]
The `isMultilingual` flag is missing. It should be added as well as the corresponding test case updated.

API reference - [api.projects.bundles.get](https://developer.crowdin.com/api/v2/#operation/api.projects.bundles.get)
Model - [Bundle.java](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/bundles/model/Bundle.java)
Test - [BundlesApiTest.java](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/test/java/com/crowdin/client/bundles/BundlesApiTest.java)

Also, the `public` modifier should be added here - [BundlesApi.java#L160](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/bundles/BundlesApi.java#L160)

**Comment by andrii-bodnar** [comment]
@Aveti79 maybe you would like to do it? Somehow it was missed in the #131

**Comment by Aveti79** [comment]
@andrii-bodnar Sure, I can take care of this, you can assign me.

**Comment by andrii-bodnar** [comment]
@Aveti79 thank you!
