### ISSUE TITLE
String Batch Operations API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#143]
Crowdin added new API endpoint - [String Batch Operations](https://developer.crowdin.com/api/v2/#operation/api.projects.strings.batchPatch).

It would be great to add the new method to this API client as well as the corresponding unit tests.

**Comment by professorabhay** [comment]
Hey @andrii-bodnar, I would like to work on that issue. 
As an beginner just need your guidance !!

**Comment by andrii-bodnar** [comment]
@professorabhay sure, thank you!

You can use similar pull requests as a reference, for example: #131, #129, #104

**Comment by andrii-bodnar** [comment]
Hey @professorabhay, please let me know if you need any assistance with this

**Comment by innomaxx** [comment]
Hello @professorabhay,
Are there any progress from you or I can take this task?

**Comment by professorabhay** [comment]
Hey @andrii-bodnar, I'm really sorry this time. I am busy with my end semester exams. I unassigned my self from that issue.
@innomaxx if you want to work on this then you can!!

**Comment by innomaxx** [comment]
@professorabhay no problem, thanks for the interest to this task and informing us. Have a nice day!
