### ISSUE TITLE
Distributions API changes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#159]
The Distribution creation API has been changed. Now you can create a distribution with the following parameters:

- `bundleIds` - array of bundle ids

The following parameters have been deprecated:

- `format`
- `exportPattern`
- `labelIds`

A Distribution response has also been changed. Now it contains the `bundleIds` field. The `format`, `exportPattern`, and `labelIds` fields are deprecated.

In addition, the `fileIds` request parameter is now _optional_.

All the changes are described in the [API documentation](https://developer.crowdin.com/api/v2/#operation/api.projects.distributions.post).

**Comment by Durdush** [comment]
Hi, Can i pick this issue. It is my first issue so just in case is there any timeline associated with it.

**Comment by andrii-bodnar** [comment]
Hi @Durdush, sure, thank you!

There is no strict timeline for this, but it would be great to finish as soon as possible since it's blocking this - https://github.com/crowdin/crowdin-cli/pull/593

**Comment by Durdush** [comment]
Thanks for the assigning. 
But i am not able to see the create branch option here. Can you please guide.

**Comment by andrii-bodnar** [comment]
@Durdush you can [Fork the repository](https://docs.github.com/en/get-started/quickstart/contributing-to-projects), create a branch then, and submit a PR after pushing the changes.
