### ISSUE TITLE
Add support for the Notifications API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#170]
Crowdin API has a new Notifications API that allows sending notifications to the project and organization members. It would be great to add support for this API in this Crowdin API client.

**API reference:**

- [Send Notification to Authenticated User](https://developer.crowdin.com/api/v2/#operation/api.notify.post) (crowdin.com)
- [Send Notification To Project Members](https://developer.crowdin.com/api/v2/#operation/api.projects.notify.post) (crowdin.com and Crowdin Enterprise)
- [Send Notification To Organization Members](https://developer.crowdin.com/enterprise/api/v2/#operation/api.notify.post) (Crowdin Enterprise)

**Comment by Durdush** [comment]
Hi @andrii-bodnar, Could you please assign me this.

**Comment by Durdush** [comment]
Hi @andrii-bodnar, Sorry for the delay. 
Here for sending notification do we have to get the list of all the authenticated users and then send the notification to users?

**Comment by andrii-bodnar** [comment]
Hi @Durdush, no, we don't need to get a list, we just need to implement methods to call the described Crowdin APIs.

**Comment by Durdush** [comment]
Hi @andrii-bodnar, here for authenticated users and organisation members url is same, so there my test cases are failing. Is it alright, can you confirm

**Comment by andrii-bodnar** [comment]
@Durdush could you please provide more details? I don't fully understand what you mean

**Comment by Durdush** [comment]
For two api, sendNotificationToAuthenticatedUsers and sendNotificationToOrganizationMembers Url is same which is 
{protocol}://{host}/api/v2/notify
So when i am creating testCases it is giving me exception of 
Duplicate key RequestMock(url=https://testOrganization.api.crowdin.com/api/v2/notify
My actual question is why two api's have same URL?
