### ISSUE TITLE
Add more Unit tests for the `core` package

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#191]
The `core` package has low code coverage by Unit tests. We need to add more Unit tests to cover the code.

**References:**

- [Source code](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/main/java/com/crowdin/client/core)
- [Existing Unit tests](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/test/java/com/crowdin/client/core)
- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-java/tree/master/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fclient%2Fcore)

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar I can pick this up.

**Comment by andrii-bodnar** [comment]
Hi @debanjanc01, any updates on this?

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar , I'm still working on it, although my speed has been super slow.

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar I'm unassigning myself in case someone else wants to pick this up. I'm not getting the time lately to polish my changes and push them.

**Comment by DecarteAdam** [comment]
Hi,
What is expected code coverage?

**Comment by andrii-bodnar** [comment]
@DecarteAdam I think that around 80-90% for the `core` package would be good

**Comment by DecarteAdam** [comment]
Hi @andrii-bodnar ,
I've just pushed.
Can you assign this to me pls ?

**Comment by DecarteAdam** [comment]
Hey @andrii-bodnar can you link this issue to my PR?

**Comment by andrii-bodnar** [comment]
Hey @DecarteAdam, thank you!

Will review it soon
