### ISSUE TITLE
Add more Unit tests for the `languages` package

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#192]
The `languages` package has low code coverage by Unit tests. We need to add more Unit tests to cover the code.

**References:**

- [Source code](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/main/java/com/crowdin/client/languages)
- [Existing Unit tests](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/test/java/com/crowdin/client/languages)
- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-java/tree/master/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fclient%2Flanguages)

**Comment by mslowiak** [comment]
Hi @andrii-bodnar 👋 
Would you mind to assign this issue to myself?

**Comment by andrii-bodnar** [comment]
Hi @mslowiak, sure, thank you!
