### ISSUE TITLE
Add more Unit tests for the `projectsgroups` package

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#193]
The `projectsgroups` package has low code coverage by Unit tests. We need to add more Unit tests to cover the code.

**References:**

- [Source code](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/main/java/com/crowdin/client/projectsgroups)
- [Existing Unit tests](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/test/java/com/crowdin/client/projectsgroups)
- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-java/tree/master/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fclient%2Fprojectsgroups)

**Comment by techrajdeep** [comment]
Hi @andrii-bodnar ,Please let me know if it is still open

**Comment by andrii-bodnar** [comment]
Hi @techrajdeep, any updates on this?
