### ISSUE TITLE
Add more Unit tests for the `reports` package

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#195]
The `reports` package has low code coverage by Unit tests. We need to add more Unit tests to cover the code.

**References:**

- [Source code](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/main/java/com/crowdin/client/reports)
- [Existing Unit tests](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/test/java/com/crowdin/client/reports)
- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-java/tree/master/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fclient%2Freports)

**Comment by chinmaym07** [comment]
Hey @andrii-bodnar , can I contribute to this ?

**Comment by andrii-bodnar** [comment]
@chinmaym07 sure, thank you!

**Comment by andrii-bodnar** [comment]
Hi @chinmaym07, any updates on this?

**Comment by DecarteAdam** [comment]
Hi!
What is expected code coverage?

**Comment by andrii-bodnar** [comment]
@DecarteAdam I think that around 80-90% for models would be good

**Comment by DecarteAdam** [comment]
Hey @andrii-bodnar 
Can you assign this to me?
Thanks

**Comment by DecarteAdam** [comment]
Hey @andrii-bodnar
Pushed! 
Can you link this issue to my PR?

**Comment by andrii-bodnar** [comment]
Hey @DecarteAdam, thank you!

Will review it soon
