### ISSUE TITLE
Add more Unit tests for the `translations` package

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#197]
The `translations` package has low code coverage by Unit tests. We need to add more Unit tests to cover the code.

**References:**

- [Source code](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/main/java/com/crowdin/client/translations)
- [Existing Unit tests](https://github.com/crowdin/crowdin-api-client-java/tree/master/src/test/java/com/crowdin/client/translations)
- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-java/tree/master/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fclient%2Ftranslations)

**Comment by techrajdeep** [comment]
hi @andrii-bodnar Please let me know if it is still open

**Comment by andrii-bodnar** [comment]
Hi @techrajdeep, it's available, assigning it to you

**Comment by Sebaszjuh** [comment]
Hi @andrii-bodnar, if this issue is open, i would like to try pick it up.

**Comment by andrii-bodnar** [comment]
Hi @Sebaszjuh, sure, assigning it to you, thank you!
