### ISSUE TITLE
Applications API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#200]
Crowdin has recently added new endpoints for managing custom applications. Support for these endpoints is missing in this Crowdin API client.

We need to add support for the following endpoints:

- [Get Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.get)
- [Update or Restore Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.put)
- [Add Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.post)
- [Delete Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.delete)
- [Edit Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.patch)

**Comment by MichalDemcak** [comment]
Hi if this issue is still free can you assign it to me ?

**Comment by MichalDemcak** [comment]
Hi do you have some comunication chanel to ask something or just email?

Dňa st 11. 10. 2023, 19:25 Andrii Bodnar ***@***.***>
napísal(a):

**Comment by andrii-bodnar** [comment]
Hi @MichalDemcak, thank you! Feel free to ask any questions here in the issue comments.

**Comment by sugan0tech** [comment]
Hi @andrii-bodnar  can i try this one?

**Comment by sugan0tech** [comment]
@andrii-bodnar  is there any specific data schema for the applications data?

**Comment by andrii-bodnar** [comment]
@sugan0tech there is no specific schema because each application can define its own schema. It's just a JSON object from an API perspective.
