### ISSUE TITLE
Report Settings Template: add the `isPublic` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#201]
The Report Settings Template API now supports the ability to create public templates. We need to add support for the `isPublic` property to this Crowdin API client.

**References:**

- [Add Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.post)
- [Get Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.get) (response)

**Comment by indra057** [comment]
i am trying to understand what to fix but i am not getting it can u describe it a little bit ..it would be of great help?? and is there any possibility that u can assign me this?

**Comment by andrii-bodnar** [comment]
@indra057 please refer to similar PRs, for example - https://github.com/crowdin/crowdin-api-client-java/pull/198/

thank you!

**Comment by indra057** [comment]
do we need to add isPublic property in this file?? 
https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/reports/model/ReportSettingsTemplate.java

**Comment by andrii-bodnar** [comment]
@indra057 yes, but please check the related code as well, we'll probably need to update some other files like in the mentioned pull request

**Comment by andrii-bodnar** [comment]
@indra057 any updates on this?
