### ISSUE TITLE
Source Files: add the `context` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#204]
The Source Files API now supports the possibility to specify the `context` for the whole file. We need to add support for the `context` property to this Crowdin API client.

**References:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get file](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get) (response)

**Comment by sugan0tech** [comment]
Hi @andrii-bodnar  can i try this issue?

**Comment by andrii-bodnar** [comment]
Hi @sugan0tech, yes, thank you!
