### ISSUE TITLE
Strings translations APIs: add new parameters support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#207]
Several String Translation API endpoints have been enhanced with new parameters support: `labelIds`, `excludeLabelIds`. These parameters should be added to this API client.

**References:**

- [List Translation Approvals](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.approvals.getMany)
- [List Translation Votes](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.votes.getMany)

**Comment by jcvdg** [comment]
Hi @andrii-bodnar, I'd like to help with this. If you can point me to the right files, that'll be really helpful too.

**Comment by jcvdg** [comment]
I found it: https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/stringtranslations/StringTranslationsApi.java

Can you assign this to me? I can work on it.

**Comment by andrii-bodnar** [comment]
Hi @jcvdg sure, thank you!

The `https://stringtranslationsapi.java` is the right file

**Comment by jcvdg** [comment]
Hi @andrii-bodnar , here's the [PR](https://github.com/crowdin/crowdin-api-client-java/pull/209). Let me know if it looks good, or if there are changes needed that I may have missed.
