### ISSUE TITLE
Security Logs API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#219]
Crowdin has recently released a new API methods to get information about security logs. It would be great to add support of these methods to the Crowdin API client.

**References:**

- [List User Security Logs](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.getMany)
- [Get User Security Log](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.get)
- [List Organization Security Logs](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.getMany) (Crowdin Enterprise)
- [Get Organization Security Log](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.get) (Crowdin Enterprise)

**Comment by Durdush** [comment]
Hi @andrii-bodnar, Can you please assign me this.

**Comment by Durdush** [comment]
Also If there is any specific timeline for this issue.

**Comment by zozulka** [comment]
Hi @Durdush !

We will check the possibility of assigning this to you and also will find out more about the timeline.

Let's keep in touch!

**Comment by Durdush** [comment]
Sure

**Comment by andrii-bodnar** [comment]
Hi @Durdush, thanks for your interest in this. Already assigned to you. There is no strict timeline for this issue.

**Comment by andrii-bodnar** [comment]
Hi @Durdush, do you have any updates on this?

**Comment by Durdush** [comment]
Hi @andrii-bodnar, its in progress will raise its PR soon.
