### ISSUE TITLE
Actualize the Webhook events list

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#221]
The events Enum is a little bit outdated and doesn't contain all the possible events.

**Code:**

https://github.com/crowdin/crowdin-api-client-java/blob/1d833ccdd3d3616a5d3b6d403b3cdc11ab12360e/src/main/java/com/crowdin/client/webhooks/model/Event.java#L5-L7

**All supported events:**

`
Items Enum: "file.added" "file.updated" "file.reverted" "file.deleted" "file.translated" "file.approved" "project.translated" "project.approved" "project.built" "translation.updated" "string.added" "string.updated" "string.deleted" "stringComment.created" "stringComment.updated" "stringComment.deleted" "stringComment.restored" "suggestion.added" "suggestion.updated" "suggestion.deleted" "suggestion.approved" "suggestion.disapproved" "task.added" "task.statusChanged" "task.deleted"
`

[API Reference](https://developer.crowdin.com/api/v2/#operation/api.projects.webhooks.post)

**Comment by codeHysteria28** [comment]
Hi @andrii-bodnar can I help with this one ? Thanks !

**Comment by andrii-bodnar** [comment]
Hi @codeHysteria28, sure, thank you!

**Comment by codeHysteria28** [comment]
hey @andrii-bodnar do I need a permission to push thanks ?

**Comment by codeHysteria28** [comment]
#222 PR Opened
