### ISSUE TITLE
Remove the `markAddedTranslationsAsDone` parameter

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#229]
this parameter is deprecated in the API and should be removed from the codebase.

**Comment by imraklr** [comment]
I would like to take up this task.

Do I need to run the unit tests after removing this parameter?

I have not found any usage of parameter `markAddedTranslationsAsDone`. So it is safe to delete without running unit tests.

**Comment by andrii-bodnar** [comment]
@imraklr sure, we'd be happy to accept the contribution!

**Comment by imraklr** [comment]
I've addressed the linting issues and amended the commit message accordingly. The force push was necessary to update the commit history. Please review the changes and let me know if there are any further adjustments needed.
