### ISSUE TITLE
Add new Report Archives API endpoints

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#241]
Crowdin has recently introduced a new feature called _Report Archives_ that allows you to see the history of your reports. This feature comes with a set of new API endpoints that you can use to interact with the report archives.

The new API endpoints should be added to the Crowdin API client.

**References:**
- [List Report Archives](https://developer.crowdin.com/api/v2/#operation/api.reports.archives.getMany)
- [Get Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.get)
- [Delete Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.delete)
- [Export Report Archive](https://developer.crowdin.com/api/v2/#operation/api.reports.archives.exports.post)
- [Check Report Archive Export Status](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.exports.get)
- [Download Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.exports.download.get)

**Comment by DecarteAdam** [comment]
Hi,
I have just added these endpoints and would like to push.
But unfortunately I can't. I have permission error.
I have created new branch from master.
Maybe I need to swich to anouther branch?

Thanks

**Comment by andrii-bodnar** [comment]
Hi @DecarteAdam, you need to fork the repo and then [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by DecarteAdam** [comment]
@andrii-bodnar Thank you for explanation!
This is my first contributing to OpenSource so I'm a newbie  :-)

**Comment by andrii-bodnar** [comment]
@DecarteAdam awesome, congrats on your first contribution, and thank you! 🚀
