### ISSUE TITLE
Don't understand the API to update a source file

### ISSUE THREAD

**Issue by eitch** [crowdin/crowdin-api-client-java#252]
I'm using the following API call to update a source file, but i can't see how to attach the actual file:

```java
UpdateFileRequest updateFileRequest = new UpdateFileRequest();
updateFileRequest.setUpdateOption(UpdateOption.KEEP_TRANSLATIONS_AND_APPROVALS);
OtherFileImportOptions importOptions = new OtherFileImportOptions();
updateFileRequest.setImportOptions(importOptions);
ResponseObject<? extends FileInfo> uploadResponse = client
        .getSourceFilesApi()
        .updateOrRestoreFile(PROJECT_ID, sourceFileId.get(), updateFileRequest);
```

Even the test cases don't really test this.

Can someone point me in the right direction?

**Comment by andrii-bodnar** [comment]
Hi @eitch, you need to upload the file to a Storage first.

See the CLI source code for the example:

https://github.com/crowdin/crowdin-cli/blob/4a28adfddbaa1d3c251072b3d18c605c9f563501/src/main/java/com/crowdin/cli/commands/actions/UploadSourcesAction.java#L184-L198

**Comment by eitch** [comment]
Ahh, thanks, just what i was looking for!
