### ISSUE TITLE
Screenshots APIs: add the `stringIds` parameter support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#256]
The List Screenshots API has a new parameter called `stringIds` which allows you to filter screenshots by multiple string identifiers.

The existing `stringId` parameter is deprecated and will be removed in the future.

Things to do:

- Add support for the `stringIds` parameter in this API client.
- Mark the `stringId' parameter as deprecated.
- Check if other parameters need to be updated.

**References:**
- [List Screenshots](https://support.crowdin.com/developer/api/v2/#tag/Screenshots/operation/api.projects.screenshots.getMany)

**Comment by cmgyqjj** [comment]
"Hey, can this task be assigned to me? If I've understood correctly, it just requires modifications in the parameters and return values of the ProjectsGroupsApi.addProject, ProjectsGroupsApi.getProject, and ProjectsGroupsApi.editProject methods to include defaultTmId and defaultGlossaryId for initiating the call."

**Comment by cmgyqjj** [comment]
Hey, can this task be assigned to me? I have carefully reviewed the documentation and have added the `stringIds`, `labelIds`, and `excludeLabelIds` parameters to the `ScreenshotsApi.listScreenshots` method. Additionally, I have marked the `stringId` parameter as deprecated.
