### ISSUE TITLE
Projects API: `defaultTmId`, `defaultGlossaryId` support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#258]
The "Add Project", "Edit Project" API endpoint now supports the `defaultTmId` and `defaultGlossaryId` parameters. This allows you to set the default Translation Memory and Glossary for a project.

**Things to do:**

- Add new parameters to the Add Project and Edit Project methods.
- The Get Project response now also includes the default TM and Glossary IDs. It should be updated to reflect this change.

**References:**

- [Add Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.post)
- [Edit Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.patch)
- [Get Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.get)

**Comment by cmgyqjj** [comment]
"Hey, can this task be assigned to me? If I've understood correctly, it just requires modifications in the parameters and return values of the ProjectsGroupsApi.addProject, ProjectsGroupsApi.getProject, and ProjectsGroupsApi.editProject methods to include defaultTmId and defaultGlossaryId for initiating the call."

**Comment by andrii-bodnar** [comment]
@cmgyqjj right, it is correct. Thank you!
