### ISSUE TITLE
AI Provider Methods

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#270]
**This is a sub-issue. See the parent issue for more details - https://github.com/crowdin/crowdin-api-client-java/issues/233**

**Comment by vedantnd111** [comment]
@andrii-bodnar could you please assign this to me?

**Comment by vedantnd111** [comment]
Published PR: https://github.com/crowdin/crowdin-api-client-java/pull/282 for this.
