### ISSUE TITLE
Fine-Tuning Methods

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#272]
**This is a sub-issue. See the parent issue for more details - https://github.com/crowdin/crowdin-api-client-java/issues/233**

**Comment by timiredmind** [comment]
@andrii-bodnar may I pick up this issue?

**Comment by andrii-bodnar** [comment]
@timiredmind sure, thank you!

**Comment by andrii-bodnar** [comment]
@timiredmind I think it would be better to wait for the https://github.com/crowdin/crowdin-api-client-java/pull/279 merge to avoid conflicts.

**Comment by timiredmind** [comment]
@andrii-bodnar alright
