### ISSUE TITLE
AI Setting Methods

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#274]
**This is a sub-issue. See the parent issue for more details - https://github.com/crowdin/crowdin-api-client-java/issues/233**

**Comment by vedantnd111** [comment]
> **This is a sub-issue. See the parent issue for more details - #233**

@andrii-bodnar May I pick this?

**Comment by andrii-bodnar** [comment]
@vedantnd111 sure, thank you!

**Comment by vedantnd111** [comment]
> @vedantnd111 sure, thank you!

Published PR: https://github.com/crowdin/crowdin-api-client-java/pull/279. Also, my tests are failing locally, I failed to understand why. Could you please take a look into it whenever possible?
Thanks!
