### ISSUE TITLE
Add "Getting Started" Section to CONTRIBUTING.md with JDK and Build Tool Information

### ISSUE THREAD

**Issue by kidobop** [crowdin/crowdin-api-client-java#285]

**Comment by Moses-Mk** [comment]
This is a simple documentation task, please assign it to me.. I will commit it today so that we can correct and merge it tomorrow before hacktoberfest closes. Please I really need this as my last contribution for this month. Thank you

**Comment by andrii-bodnar** [comment]
@Moses-Mk, just assigned it to you. I would suggest adding the corresponding section to the [Your First Code Contribution](https://github.com/crowdin/crowdin-api-client-java/blob/master/CONTRIBUTING.md#your-first-code-contribution).

**Comment by Moses-Mk** [comment]
Thank you, I have completed my work, please look into it and see if it meets your specifications and info me on the necessary changes if any and if not, please you can then merge it.

Thank you very much for allowing me contribute
