### ISSUE TITLE
Bad crowdin api url

### ISSUE THREAD

**Issue by Chikouni** [crowdin/crowdin-api-client-java#45]
There is a dot before url in CrowdinApi class -> line 46
`if (credentials.getOrganization() != null) {
                this.url = "https://" + credentials.getOrganization() + ".api.crowdin.com/api/v2";
            } else {
                this.url = "https://api.crowdin.com/api/v2";
            }`

**Comment by andrii-bodnar** [comment]
Hi @Chikouni !

There is no issue here, this URL is valid and consist of `"https://"` + `credentials.getOrganization()` + `".api.crowdin.com/api/v2"`

Resulting URL: `https://organization.api.crowdin.com/api/v2`
