### ISSUE TITLE
Bad named object and wrong param

### ISSUE THREAD

**Issue by Chikouni** [crowdin/crowdin-api-client-java#46]
the object : `ExportPrjoectTranslationRequest` are bad named and in the object there is :
 `  private String targetLanguageId;
    private String format;
    private List<Long> branchIds;
    private List<Long> directoryIds;
    private List<Long> fileIds;
    private Boolean skipUntranslatedStrings;
    private Boolean skipUntranslatedFiles;
    private Integer exportWithMinApprovalsCount;
`

But on the reference API v2 this is `exportApprovedOnly`   instead `exportWithMinApprovalsCount`

Because when the client send request, it throw exception because
 `"errors": [
                    {
                        "code": "notFound",
                        "message": "Field 'exportWithMinApprovalsCount' Not Found"
                    }`

**Comment by BozhenaDobrovolska** [comment]
Hi there!

Thank you for reporting!
 
Our technical team will fix it soon,

**Comment by Chikouni** [comment]
Hi @BozhenaDobrovolska  
I make a PR for the fix

Best regard

**Comment by Chikouni** [comment]
Fixed !
Thanks 
#47
