### ISSUE TITLE
XmlFileImportOptions deserialization issue

### ISSUE THREAD

**Issue by kobyzau** [crowdin/crowdin-api-client-java#58]
XmlFileImportOptions contains field translatableElements.
In java com.crowdin.client.sourcefiles.model.XmlFileImportOptions it is represented as a list of Strings.
However, the api returns it as a key-value map what cause exception in deserialization.

**Comment by andrii-bodnar** [comment]
Hi @kobyzau!
Could you please clarify which API method caused this issue?

**Comment by kobyzau** [comment]
I used GET https://api.crowdin.com/api/v2/projects/{projectId}/files/{fileId}
In SourceFilesApi it's the method _public ResponseObject<? extends FileInfo> getFile(Long projectId, Long fileId)_

**Comment by andrii-bodnar** [comment]
@kobyzau sorry, but we can't reproduce this issue. API returns an array for translatable elements:

![Screenshot from 2021-04-26 12-28-28](https://user-images.githubusercontent.com/29282228/116061021-0e914b00-a68b-11eb-9cf5-2f7641df614b.png)

Could you please provide detailed steps to reproduce and a sample file?
