### ISSUE TITLE
Remove `limit` and `offset` parameters from `listWorkflowSteps` method

### ISSUE THREAD

**Issue by kptfh** [crowdin/crowdin-api-client-java#75]
Crowdin returns error if I try to pass limit and offset
AFAIK Crowdin doesn't need them anymore.

```
public ResponseList<WorkflowStep> listWorkflowSteps(Long projectId, Integer limit, Integer offset) throws HttpException, HttpBadRequestException {
        Map<String, Optional<Integer>> queryParams = HttpRequestConfig.buildUrlParams("limit", Optional.ofNullable(limit), "offset", Optional.ofNullable(offset));
        WorkflowStepResponseList workflowStepResponseList = (WorkflowStepResponseList)this.httpClient.get(this.url + "/projects/" + projectId + "/workflow-steps", new HttpRequestConfig(queryParams), WorkflowStepResponseList.class);
        return WorkflowStepResponseList.to(workflowStepResponseList);
    }
```

**Comment by kptfh** [comment]
Correct

**Comment by KatelynKunzmann** [comment]
Okay, I finished. Do you want me to make a pull request so you can evaluate if it is correct?

**Comment by KatelynKunzmann** [comment]
Okay, that's what I did. Opening a PR now.

**Comment by KatelynKunzmann** [comment]
Let me know if anything needs changed!

**Comment by andrii-bodnar** [comment]
@kptfh @KatelynKunzmann merged the PR. Please let me know if you need a new version release now.

**Comment by VadimMoroz** [comment]
Hello.
Changing API without maintaining backward compatibility leads to production incidents on client sides.
Are there any option to prevent such breaking changes?

The solution is great, but such uncontrolled issues have impact on stability.
Thanks

**Comment by andrii-bodnar** [comment]
@VadimMoroz it was an issue related only to the Java API Client. There have never been the `limit` and `offset` parameters in the "List Workflow Steps" API. Probably, we should have released a minor version instead of a patch for this change.
