### ISSUE TITLE
Join SUBORDINATING and CONJUNCTION in PartOfSpeech enum

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#79]
Code:

https://github.com/crowdin/crowdin-api-client-java/blob/dc1741d00eb78202a7126f2d84db990d57593d47/src/main/java/com/crowdin/client/glossaries/model/PartOfSpeech.java#L5-L8

API Reference - [api.glossaries.terms.post](https://support.crowdin.com/enterprise/api/#operation/api.glossaries.terms.post)

**Comment by s-aLman** [comment]
@andrii-bodnar pushed changes for this.
