### ISSUE TITLE
Add Bundles API endpoints

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#89]
New API endpoints:

- [Bundles](https://developer.crowdin.com/api/v2/#tag/Bundles) (crowdin.com)
- [Bundles](https://developer.crowdin.com/enterprise/api/v2/#tag/Bundles) (Crowdin Enterprise)

**Comment by s-aLman** [comment]
@andrii-bodnar Please assign this to me. Thanks.

**Comment by s-aLman** [comment]
@andrii-bodnar Pushed changes for Bundles API. Please check. Thanks. 🙂
