### ISSUE TITLE
Update Distributions API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#90]
Added new request fields - [api.projects.distributions.post](https://developer.crowdin.com/api/v2/#operation/api.projects.distributions.post)

\+ distribution response object and patch are also updated

crowdin.com and Crowdin Enterprise

**Comment by s-aLman** [comment]
Hi @andrii-bodnar, I have pushed changes for this task. Updated request and response for post endpoint in Distribution API. Currently, have not added post endpoint for Report Settings Template. Removed stuff for that. You can merge this PR for this task as of now. Working on Report Settings Template Endpoint. Will create a new PR for that. Thanks.

**Comment by andrii-bodnar** [comment]
@s-aLman great, thanks a lot! 🤘

**Comment by s-aLman** [comment]
@andrii-bodnar okay, sure then. Will push the changes in new PR.

**Comment by andrii-bodnar** [comment]
@s-aLman also, it would be great to push the Distributions API changes as a separate PR

**Comment by s-aLman** [comment]
@andrii-bodnar Created new PR for this task. Please check.
