### ISSUE TITLE
Auto generated docs

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#94]
As a Crowdin Java API client user, I would like to have online docs to navigate and explore the client resources, methods, parameters, etc.

Examples:
- [Crowdin API Client PHP docs](https://crowdin.github.io/crowdin-api-client-php/packages/Crowdin.html)
- [Crowdin API Client JS docs](https://crowdin.github.io/crowdin-api-client-js/modules.html)
- [Crowdin API Client .NET docs](https://crowdin.github.io/crowdin-api-client-dotnet/api/Crowdin.Api.html)

These docs should be generated using GH Actions and deployed to GH Pages. Workflow example: [docs.yml](https://github.com/crowdin/crowdin-api-client-js/blob/master/.github/workflows/docs.yml)

The possible tool for that is [javadoc](https://www.geeksforgeeks.org/what-is-javadoc-tool-and-how-to-use-it/).

Steps:

- [ ] Explore tools to generate such docs, and choose the best one.
- [ ] Create a config and provide a command to generate the docs.
- [ ] If needed, add additional annotations to the API Client code (ignore some unneeded methods in docs, add some method or parameters descriptions, etc).
- [ ] Setup the  GH workflow. @andrii-bodnar can help with that.
- [ ] Setup the GH pages feature for the repo. @andrii-bodnar

**Comment by s-aLman** [comment]
@andrii-bodnar I think, we should try with Java 8. As we have this version compatible to the gradle build file.

**Comment by andrii-bodnar** [comment]
@s-aLman everything works great! 🚀 

I just created the workflow (#111) and now the docs are available - [crowdin.github.io/crowdin-api-client-java](https://crowdin.github.io/crowdin-api-client-java/)

**Comment by andrii-bodnar** [comment]
@s-aLman is it possible to add links for each API method? https://www.baeldung.com/javadoc-see-vs-link

It would be great to include these links.

For example, how it is done in other our API clients:

- https://github.com/crowdin/crowdin-api-client-js/blob/master/src/bundles/index.ts
- https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Bundles/BundlesApiExecutor.cs
- https://github.com/crowdin/crowdin-api-client-python/blob/main/crowdin_api/api_resources/bundles/resource.py
- https://github.com/crowdin/crowdin-api-client-php/blob/master/src/CrowdinApiClient/Api/BundleApi.php
- https://github.com/crowdin/crowdin-api-client-ruby/blob/main/lib/crowdin-api/api_resources/bundles.rb

So these links then become available on the online doc:

![screenshot-crowdin github io-2022 11 05-14_04_33](https://user-images.githubusercontent.com/29282228/200118996-6f4730ee-ec4d-4a7b-8620-be1b630bda26.png)
e Docs:

**Comment by s-aLman** [comment]
Sure, I will work on that.

**Comment by s-aLman** [comment]
@andrii-bodnar is this fine ?
![addedlink](https://user-images.githubusercontent.com/68873632/200166565-c4db9544-d05c-4df9-abe2-d28d25ad928a.jpg)

**Comment by andrii-bodnar** [comment]
@s-aLman looks great! 🚀 

But I would suggest renaming `API Enterprise Documentation` -> `Enterprise API Documentation`

**Comment by s-aLman** [comment]
sure, I will do that.
