### ISSUE TITLE
Report Settings Templates API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-java#99]
**New API endpoints:**
  - [api.projects.reports.settings-templates.getMany](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.getMany)
  - [api.projects.reports.settings-templates.post](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.post)
  - [api.projects.reports.settings-templates.get](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.get)
  - [api.projects.reports.settings-templates.patch](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.patch)
  - [api.projects.settings-templates.delete](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.settings-templates.delete)

These new endpoints should be reflected in this API client and covered by Unit tests.

**Comment by s-aLman** [comment]
Hey @andrii-bodnar, I would like to work on this. Could you please assign this to me?

**Comment by andrii-bodnar** [comment]
Hi @s-aLman, sure, thank you! Please let me know if you need any assistance with that

**Comment by andrii-bodnar** [comment]
@s-aLman great! Please check just a minor comment regarding code formatting, and then will merge
